### ISSUE TITLE
Why not __all__ ?

### ISSUE THREAD

**Issue by nicolas-leydet** [Never-Over/modguard#27]
Why did you choose not to use __all__  instead Boundary objects and decorators?

**Comment by emdoyle** [comment]
Fair question! We should probably add this to the FAQ.

The main reason is that \_\_all\_\_ is less expressive and less ergonomic. More specifically:

- modguard allows specifying *where* each public member is allowed to be used (with the allowlist parameter), as opposed to allowing them to be imported anywhere when importing from \*
- modguard.public is applied typically right next to the member being exported, which improves visibility for future maintainers

We also considered at least reading any existing \_\_all\_\_ assignments as public, but we kept our logic separate and ignore \_\_all\_\_ when running `modguard check`. This provides a few advantages:

- when you first install modguard and run it, you're by default in a passing state
- boundaries and public members are defined with a single interface (you don't have to check multiple places)
- we have a hook to support future inline behavior at the function/class/variable definition
